### ISSUE TITLE
rename not working as expected

### ISSUE THREAD

**Issue by enboig** [LibrePhotos/librephotos-docker#80]
I renamed containers name in `.env` and when I run `make rename` they aren't renamed in `docker-compose.yml`. I renamed them manually in `docker-compose.yml` but then if I run `make rename` they are overwrite.
Could it be that `.env` is not used?

Reading `Makefile` file it appear it is using `librephotos.env` and not `.env`

**Comment by phockett** [comment]
I just ran into this too - to fix, just change the third line of the Makefile:

https://github.com/LibrePhotos/librephotos-docker/blob/01a4565ac8b1eee189438c3159776f1ad563daf6/Makefile#L3

The default case is `include librephotos.env`.

To run with your own file, just change the name as required, e.g. change to `include .env` to use your current `.env` file for the renaming.

**Comment by phockett** [comment]
Actually, after fixing the above, I now have other issues:

1. Proxy fails due to renamed `frontend` container. I fixed this by manually changing the `nginx.conf` file (has hard-coded frontend and backend names) and rebuilding the proxy container locally.

File:
https://github.com/LibrePhotos/librephotos-docker/blob/main/proxy/nginx.conf

Rebuild with: `docker build -t proxy_archive --no-cache .` from the `/proxy` directory to push local changes to the build.


2. I now am stuck with Nginx config settings, which are giving problems with the `ALLOWED_HOST`, which also seems to be expecting `backend` as the container name (my container is currently called `backend_archive`).

Error in logs:

```
backend_archive   | django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'backend'. You may need to add 'backend' to ALLOWED_HOSTS.
```

This should be set from the ENV settings I think, see https://github.com/LibrePhotos/librephotos/blob/04ac679400c9424d122bd1d71f4012423526b3b3/librephotos/settings/production.py#L48

In the main `docker-compose.yml` this should be configured:

```
    environment:
      - BACKEND_HOST=backend_archive
```

... but doesn't seem to be working for me at the moment. I'm now troubleshooting to see if I can find out where the issue is.

**Comment by rjdodd00** [comment]
I know this is old, but did this ever get resolved? I am having the same problem but on a fresh install

**Comment by phockett** [comment]
Nope, I never got it working correctly - I ended up just giving up on
running multiple stacks, and just used multiple logins instead (although
this has different issues!) :shrug:.

**Comment by derneuere** [comment]
Renaming is now removed, hence no longer an issue.
